name: ci-fullstack-workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'  # Every Sunday at midnight

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: cd backend && npm install

      - name: Run tests
        run: cd backend && npm test

      - name: Lint code
        run: cd backend && npm run lint

      - name: Print completion message
        run: echo "Hello ${{ github.actor }}. You pushed to ${{ github.repository }} at $(date)."
